Improve checking if in a git repo
Updated CATGIT_VERSION to "1.0.1 25-06-2025".

diff --git a/catgit b/catgit
--- a/catgit
+++ b/catgit
@@ -26,7 +26,7 @@
 # - Cody Boone Ferguson (@xexyl)
 #
 
-export CATGIT_VERSION="1.0.0-1 11-10-2023" # format: major.minor.patch-release DD-MM-YYYY
+export CATGIT_VERSION="1.0.1 25-06-2025" # format: major.minor.patch-release DD-MM-YYYY
 
 USAGE="usage: $(basename "$0") [-h] [-V] [-v level] [-x] [-c cat] [-o options] [-n] <glob...>
 
@@ -47,10 +47,10 @@ catgit version: $CATGIT_VERSION"
 
 
 # before we do anything check that this is a git repo!
-git status 2>/dev/null 1>&2
-status="$?"
-if [[ "$status" -ne 0 ]]; then
-    echo "$(basename "$0"): ERROR: ${PWD} not a git repository" 1>&2
+if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
+    echo "$USAGE" 1>&2
+    echo 1>&2
+    echo "$(basename "$0"): ERROR: ${PWD} is not a git repository" 1>&2
     exit 1
 fi
 
